USE QLST
GO
-- Tạo kiểu dữ liệu cho các sản phẩm trong hóa đơn
IF NOT EXISTS(SELECT * FROM SYS.types WHERE name = 'CART_ITEM')
	CREATE TYPE CART_ITEM AS TABLE
	(
		MASP VARCHAR(10),
		SOLUONG INT
	)
GO

CREATE OR ALTER PROCEDURE USP_PROCESS_NEW_ORDER
    @MANV VARCHAR(10),
    @MAKH VARCHAR(10),
    @MAPG VARCHAR(10),
    @Cart_Items CART_ITEM READONLY
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON
	
	BEGIN TRY
		BEGIN TRAN
			-- Sort lại thứ tự sản phẩm để tránh deadlock khi read @Cart_Items(A,B) và (B,A)
			DECLARE @SORTED_CART CART_ITEM
			INSERT INTO @SORTED_CART
			SELECT *
			FROM @Cart_Items
			ORDER BY MASP ASC

			-- 1. VALIDATION CƠ BẢN --
			-- Kiểm tra nhân viên có tồn tại không
			IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV)
				THROW 50001, N'Nhân viên không tồn tại', 1
			-- Kiểm tra tồn kho sản phẩm
			IF EXISTS(
				SELECT 1
				FROM @SORTED_CART C 
				JOIN SANPHAM S WITH(UPDLOCK, HOLDLOCK) ON C.MASP = S.MASP
				WHERE C.SOLUONG > S.TONKHO
			)
				THROW 50002, N'Một số sản phẩm không đủ tồn kho', 1

			-- Kiểm tra phiếu giảm giá
			DECLARE @PHANTRAMGIAMVOUCHER FLOAT = 0
			IF @MAPG IS NOT NULL 
			BEGIN
				SELECT @PHANTRAMGIAMVOUCHER = PHANTRAMGIAM
				FROM PHIEUGIAMGIA WITH(UPDLOCK)
				WHERE @MAPG = MAPG AND TRANGTHAI = N'Chưa dùng'

				IF @PHANTRAMGIAMVOUCHER IS NULL
					THROW 50003, N'Phiếu giảm giá không hợp lệ hoặc đã sử dụng', 1
			END
		
			-- Lấy thông tin khách hàng và cấp độ thẻ(nếu có)
			DECLARE @ISMEMBER BIT = 0
			DECLARE @MACAPDO VARCHAR(10) = NULL

			SELECT @ISMEMBER = 1, @MACAPDO = MACAPDO
			FROM KH_THANHVIEN
			WHERE MAKH = @MAKH

			-- 2. Tạo hóa đơn --
			DECLARE @MAHD VARCHAR(10)
			DECLARE @LASTID INT

			SELECT TOP 1 @LASTID = CAST(SUBSTRING(MAHD, 3, LEN(MAHD)) AS INT)
			FROM HOADON WITH (UPDLOCK, HOLDLOCK)
			ORDER BY LEN(MAHD) DESC, MAHD DESC
	
			SET @LASTID = ISNULL(@LASTID, 0) + 1
			SET @MAHD = 'HD' + RIGHT('00' + CAST(@LASTID AS VARCHAR(10)), 2)
			-- Thêm dữ liệu tạm thời vào hóa đơn
			INSERT INTO HOADON(MAHD, NGAYLAP, TONGTIEN, MANV, MAPG, MAKH)
			VALUES (@MAHD, GETDATE(), 0, @MANV, @MAPG, @MAKH)

			-- 3. XỬ LÝ CHI TIẾT & TÍNH TOÁN KHUYẾN MÃI --
			-- SỬ DỤNG BẢNG PHỤ ĐỂ TÍNH TOÁN TRƯỚC KHI INSERT
			DECLARE @TEMPDETAILS TABLE
			(
				MASP VARCHAR(10),
				SOLUONG INT,
				DONGIA INT,
				MAKM VARCHAR(10),
				TILEGIAM FLOAT,
				SL_DUOC_GIAM INT, --MAX = 3
				THANHTIEN INT
			)

			INSERT INTO @TEMPDETAILS (MASP, SOLUONG, DONGIA, MAKM, TILEGIAM, SL_DUOC_GIAM, THANHTIEN)
			SELECT 
				C.MASP,
				C.SOLUONG,
				S.DONGIA,
				BESTKM.MAKM, -- LẤY TỪ OUTER APPLY
				ISNULL(BESTKM.TILEGIAM, 0), -- LẤY TỪ OUTER APPLY
				-- LOGIC TÍNH SỐ LƯỢNG ĐƯỢC GIẢM
				CASE
					WHEN BESTKM.MAKM IS NOT NULL THEN
						CASE WHEN C.SOLUONG > 3 THEN 3 ELSE C.SOLUONG END
					ELSE 0
				END AS SL_DUOC_GIAM,
				-- LOGIC TÍNH THÀNH TIỀN
				-- (Số lượng được giảm * Giá giảm) + (Số lượng vượt quá * Giá gốc)
				CAST (
					(
						CASE
							WHEN BESTKM.MAKM IS NOT NULL THEN
								(CASE WHEN C.SOLUONG > 3 THEN 3 ELSE C.SOLUONG END) * S.DONGIA * (1 - ISNULL(BESTKM.TILEGIAM, 0))
							ELSE 0
						END
					)
					+
					(
						CASE
							WHEN BESTKM.MAKM IS NOT NULL AND C.SOLUONG > 3 THEN (C.SOLUONG - 3) * S.DONGIA
							WHEN BESTKM.MAKM IS NULL THEN C.SOLUONG * S.DONGIA
							ELSE 0
						END
					)
					AS INT
				) AS THANHTIEN 

			FROM @SORTED_CART C
			JOIN SANPHAM S ON C.MASP = S.MASP
			-- Tìm khuyến mãi hợp lệ nhất
			OUTER APPLY (
				SELECT TOP 1 CT.MAKM, CT.TILEGIAM
				FROM CHITIETKM CT WITH(UPDLOCK)
				JOIN KHUYENMAI KM ON CT.MAKM = KM.MAKM
				WHERE CT.MASP = S.MASP
				AND KM.NGAYBATDAU <= GETDATE()
				AND KM.NGAYKETTHUC >= GETDATE()
				AND CT.SOLUONG > 0 -- SỐ LƯỢNG KHUYẾN MÃI ĐANG CÒN
				AND (
					-- Loại 1: FLASH SALE(ISMEMBER = 0) - ĐỘ ƯU TIÊN CAO NHẤT
					KM.ISMEMBER = 0
					OR
					-- Loại 2: MEMBER SALE(ISMEMBER = 1) -- ĐỘ ƯU TIÊN THẤP HƠN, CHỈ ÁP DỤNG CHO THÀNH VIÊN
					(
						KM.ISMEMBER = 1
						AND @ISMEMBER = 1
						AND EXISTS (SELECT 1 FROM MEMBER_SALE MS WHERE MS.MAKM = KM.MAKM AND MS.MACAPDO = @MACAPDO)
					)
				)
				-- SẮP XẾP THEO ĐỘ ƯU TIÊN
				-- FLASH SALE(ISMEMBER = 0) ƯU TIÊN HƠN MEMBER SALE(ISMEMBER = 1)
				ORDER BY KM.ISMEMBER ASC, CT.TILEGIAM DESC
			) AS BESTKM
			-- Insert vào bảng chính thức
			INSERT INTO CHITIETHOADON (MAHD, MASP, SOLUONG, THANHTIEN, MAKM)
			SELECT @MAHD, MASP, SOLUONG, THANHTIEN, MAKM
			FROM @TEMPDETAILS

			-- 4. Trừ tồn kho sản phẩm --
			UPDATE S
			SET	S.TONKHO -= C.SOLUONG
			FROM SANPHAM S
			JOIN @SORTED_CART C ON C.MASP = S.MASP

			-- 5. Trừ số lượng khuyến mãi --
			UPDATE CT
			SET CT.SOLUONG -= T.SL_DUOC_GIAM
			FROM CHITIETKM CT
			JOIN @TEMPDETAILS T ON CT.MASP = T.MASP AND CT.MAKM = T.MAKM
			WHERE T.MAKM IS NOT NULL AND T.SL_DUOC_GIAM > 0

			-- 6. Cập nhật tổng tiền hóa đơn & voucher --
			DECLARE @TONGTIEN INT = 0
			SELECT @TONGTIEN = SUM(THANHTIEN)
			FROM CHITIETHOADON CT
			WHERE CT.MAHD = @MAHD

			UPDATE HOADON
			SET TONGTIEN = CAST(@TONGTIEN * (1 - @PHANTRAMGIAMVOUCHER) AS INT)
			WHERE MAHD = @MAHD

			IF @MAPG IS NOT NULL
				UPDATE PHIEUGIAMGIA SET TRANGTHAI = N'Đã dùng' WHERE MAPG = @MAPG
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRAN
		THROW
	END CATCH
END
GO

DECLARE @CART_ITEM CART_ITEM
INSERT INTO @CART_ITEM
    (MASP, SOLUONG)
VALUES
    ('SP01', 10),
    ('SP02', 30)
EXEC USP_PROCESS_NEW_ORDER 'NV01', 'KH01', 'PG01', @CART_ITEM
GO