USE QLST
GO
CREATE OR ALTER PROCEDURE USP_ADD_THANH_VIEN
    @MANV VARCHAR(10),
    @HOTEN NVARCHAR(50),
    @SDT VARCHAR(10),
    @DIACHI NVARCHAR(100),
    @NGAYSINH DATE
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON

	-- 1. VALIDATION --
	-- KIỂM TRA NHÂN VIÊN TỒN TẠI HAY KHÔNG
	IF NOT EXISTS(SELECT 1 FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
        RAISERROR(N'Mã nhân viên không hợp lệ.', 16, 1);
        RETURN;
    END
	-- KIỂM TRA SĐT ĐÃ TỒN TẠI CHƯA
	IF EXISTS(SELECT 1 FROM KHACHHANG WHERE SDT = @SDT)
	BEGIN
		RAISERROR(N'Số điện thoại đã tồn tại', 16, 1)
		RETURN
	END
	-- KIỂM TRA NGÀY SINH HỢP LỆ KHÔNG
	IF @NGAYSINH >= GETDATE()
	BEGIN
        RAISERROR(N'Ngày sinh không được lớn hơn hoặc bằng ngày hiện tại.', 16, 1);
        RETURN;
    END
	
	BEGIN TRY
		BEGIN TRAN
			-- 2. TẠO MAKH
			DECLARE @MAX INT
			DECLARE @MAKH VARCHAR(10)
			
			SELECT TOP 1 @MAX = CAST(SUBSTRING(MAKH, 3, LEN(MAKH)) AS INT)
			FROM KHACHHANG WITH (UPDLOCK, HOLDLOCK)
			ORDER BY LEN(MAKH) DESC, MAKH DESC

			SET @MAX = ISNULL(@MAX, 0) + 1
			SET @MAKH = 'KH' + RIGHT('00' + CAST(@MAX AS VARCHAR(10)), 2)
			-- 3. INSERT VAO KHACHHANG
			INSERT INTO KHACHHANG (MAKH, HOTEN, SDT, DIACHI, ISTHANHVIEN)
			VALUES (@MAKH, @HOTEN, @SDT, @DIACHI, 1)
			-- 4. INSERT VAO KH_THANHVIEN
			INSERT INTO KH_THANHVIEN (MAKH, NGAYDANGKY, NGAYSINH, MANV, MACAPDO)
			VALUES (@MAKH, GETDATE(), @NGAYSINH, @MANV, 'LV1')

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRAN
		THROW
	END CATCH
END
GO
EXEC USP_ADD_THANH_VIEN 'NV04', N'NGÔ THẾ ĐẠT', '0987654321', N'100 Nguyễn Văn Cừ, TP.HCM', '2005-10-01';
GO
