USE QLST
GO
CREATE OR ALTER PROCEDURE USP_ADD_SAN_PHAM_TO_KHUYEN_MAI
    @MAKM VARCHAR(10),
    @MASP VARCHAR(10),
    @SOLUONG INT,
    @TILEGIAM FLOAT
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON

	DECLARE @TONKHOHIENTAI INT, @TONGSLKHUYENMAIDAGAN INT

	SELECT @TONKHOHIENTAI = TONKHO
	FROM SANPHAM
	WHERE MASP = @MASP

	SELECT @TONGSLKHUYENMAIDAGAN = SUM(SOLUONG)
	FROM CHITIETKM
	WHERE MASP = @MASP

	-- 1. Kiểm tra ràng buộc về tỉ lệ giảm giá
	IF @TILEGIAM <= 0 OR @TILEGIAM >= 1
	BEGIN
		RAISERROR(N'Tỷ lệ giảm giá không hợp lệ', 16, 1)
		RETURN
	END

	-- 2. Kiểm tra tồn tại và hiệu lực của KM
	IF NOT EXISTS(
		SELECT *
		FROM KHUYENMAI
		WHERE @MAKM = MAKM AND NGAYKETTHUC >= GETDATE()
	)
	BEGIN
		RAISERROR(N'Chương trình khuyến mãi không tồn tại hoặc đã kết thúc', 16, 1)
		RETURN
	END

	-- 3. Kiểm tra tồn kho và tổng số lượng khuyến mãi
	IF (@TONGSLKHUYENMAIDAGAN + @SOLUONG >= @TONKHOHIENTAI)
	BEGIN
		DECLARE @ERRORMSG VARCHAR(200);
		SET @ERRORMSG = N'Không hợp lệ! Tổng số lượng khuyến mãi(' + CAST(@TONGSLKHUYENMAIDAGAN + @SOLUONG AS VARCHAR) + N') vượt quá số tồn kho hiện tại(' + CAST(@TONKHOHIENTAI AS VARCHAR) + N')'
		RAISERROR(@ERRORMSG, 16, 1)
		RETURN
	END

	-- 4. Thực hiện insert
	BEGIN TRY
		BEGIN TRANSACTION
		IF EXISTS(SELECT 1 FROM CHITIETKM WHERE MAKM = @MAKM AND MASP = @MASP)
			UPDATE CHITIETKM 
			SET SOLUONG += @SOLUONG,
				TILEGIAM = @TILEGIAM
			WHERE MAKM = @MAKM AND MASP = @MASP
		ELSE
			INSERT INTO CHITIETKM (MASP, MAKM, SOLUONG, TILEGIAM)
			VALUES (@MASP, @MAKM, @SOLUONG, @TILEGIAM)
		
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRAN
		THROW
	END CATCH
END
GO
EXEC USP_ADD_SAN_PHAM_TO_KHUYEN_MAI 'KM30', 'SP01', 10, 0.2
