USE MASTER
GO
IF EXISTS(SELECT *
FROM SYS.DATABASES
WHERE name = 'QLST')
BEGIN
	ALTER DATABASE QLST SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE QLST
END
GO
CREATE DATABASE QLST
GO
USE QLST
GO
----CREATE TABLE----
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	VAITRO NVARCHAR(50) NOT NULL CHECK(VAITRO IN(N'Chăm sóc khách hàng', N'Quản lý ngành hàng', N'Xử lý đơn hàng', N'Quản lý kho hàng', N'Kinh doanh'))
)

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	SDT VARCHAR(10),
	DIACHI NVARCHAR(100),
	ISTHANHVIEN BIT DEFAULT 0
)

CREATE TABLE CAPDOTHE
(
	MACAPDO VARCHAR(10) PRIMARY KEY,
	TENCAPDO NVARCHAR(50) UNIQUE,
	TONGTIENTOITHIEU INT CHECK(TONGTIENTOITHIEU >= 0),
	PHANTRAMGIAMSN FLOAT CHECK(PHANTRAMGIAMSN >= 0)
)

CREATE TABLE KH_THANHVIEN
(
	MAKH VARCHAR(10) PRIMARY KEY,
	NGAYDANGKY DATE,
	NGAYSINH DATE,
	MANV VARCHAR(10),
	MACAPDO VARCHAR(10)

		FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MACAPDO) REFERENCES CAPDOTHE(MACAPDO),
	CHECK(NGAYDANGKY > NGAYSINH)
)

CREATE TABLE PHIEUGIAMGIA
(
	MAPG VARCHAR(10) PRIMARY KEY,
	PHANTRAMGIAM FLOAT CHECK(PHANTRAMGIAM > 0),
	TRANGTHAI NVARCHAR(10) NOT NULL CHECK(TRANGTHAI IN(N'Đã dùng', N'Chưa dùng')),
	MAKH VARCHAR(10)

		FOREIGN KEY(MAKH) REFERENCES KH_THANHVIEN(MAKH)
)

CREATE TABLE SOTIENTIEU
(
	MAKH VARCHAR(10),
	NAM INT CHECK(NAM > 0),
	SOTIENDATIEU INT CHECK(SOTIENDATIEU >= 0) DEFAULT 0

		PRIMARY KEY(MAKH,NAM)
		FOREIGN KEY(MAKH) REFERENCES KH_THANHVIEN(MAKH)
)

CREATE TABLE KHUYENMAI
(
	MAKM VARCHAR(10) PRIMARY KEY,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	MANV VARCHAR(10),
	ISMEMBER BIT

		FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	CHECK(NGAYKETTHUC >= NGAYBATDAU)
)

CREATE TABLE MEMBER_SALE
(
	MAKM VARCHAR(10),
	MACAPDO VARCHAR(10)

		PRIMARY KEY(MAKM, MACAPDO)
		FOREIGN KEY(MAKM) REFERENCES KHUYENMAI(MAKM),
	FOREIGN KEY(MACAPDO) REFERENCES CAPDOTHE(MACAPDO)
)

CREATE TABLE DANHMUC
(
	MADM VARCHAR(10) PRIMARY KEY,
	CHUNGLOAI NVARCHAR(50) UNIQUE,
	MANV VARCHAR(10)

		FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE NHASANXUAT
(
	MANSX VARCHAR(10) PRIMARY KEY,
	TENNSX NVARCHAR(50),
	DIACHI NVARCHAR(100),
	EMAIL VARCHAR(50) UNIQUE,
	SDT VARCHAR(10)
)

CREATE TABLE SANPHAM
(
	MASP VARCHAR(10) PRIMARY KEY,
	TENSANPHAM NVARCHAR(50),
	DONGIA INT CHECK(DONGIA > 0),
	MOTASP NVARCHAR(MAX),
	TONKHO INT DEFAULT 0,
	SOLUONGTOIDA INT CHECK(SOLUONGTOIDA > 0),
	MADM VARCHAR(10),
	MANSX VARCHAR(10)

		FOREIGN KEY(MADM) REFERENCES DANHMUC(MADM),
	FOREIGN KEY(MANSX) REFERENCES NHASANXUAT(MANSX),
	CHECK(TONKHO <= SOLUONGTOIDA)
)

CREATE TABLE CHITIETKM
(
	MASP VARCHAR(10),
	MAKM VARCHAR(10),
	SOLUONG INT CHECK(SOLUONG > 0),
	TILEGIAM FLOAT CHECK(TILEGIAM > 0 AND TILEGIAM <= 1)

		PRIMARY KEY(MASP, MAKM),
	FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
	FOREIGN KEY(MAKM) REFERENCES KHUYENMAI(MAKM)
)

CREATE TABLE HOADON
(
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYLAP DATE DEFAULT GETDATE(),
	TONGTIEN INT CHECK(TONGTIEN >= 0) DEFAULT 0,
	MANV VARCHAR(10),
	MAPG VARCHAR(10) NULL,
	MAKH VARCHAR(10)

		FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MAPG) REFERENCES PHIEUGIAMGIA(MAPG),
	FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CHITIETHOADON
(
	MAHD VARCHAR(10),
	MASP VARCHAR(10),
	SOLUONG INT CHECK(SOLUONG > 0),
	THANHTIEN INT CHECK(THANHTIEN >= 0),
	MAKM VARCHAR(10) NULL

		PRIMARY KEY(MAHD, MASP)
		FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
	FOREIGN KEY(MAKM) REFERENCES KHUYENMAI(MAKM)
)

CREATE TABLE DONDATHANG
(
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYLAP DATE DEFAULT GETDATE(),
	SOLUONGDAT INT CHECK(SOLUONGDAT > 0),
	SOLUONGDANHAN INT CHECK(SOLUONGDANHAN >= 0) DEFAULT 0,
	TRANGTHAI NVARCHAR(30) CHECK(TRANGTHAI IN(N'Chưa giao', N'Đã giao một phần', N'Đã giao đủ')),
	MANV VARCHAR(10),
	MASP VARCHAR(10)

		FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
	CHECK(SOLUONGDANHAN <= SOLUONGDAT)
)

CREATE TABLE PHIEUNHAPHANG
(
	MAPN VARCHAR(10) PRIMARY KEY,
	NGAYNHAP DATE DEFAULT GETDATE(),
	MANSX VARCHAR(10)

		FOREIGN KEY(MANSX) REFERENCES NHASANXUAT(MANSX)
)

CREATE TABLE CHITIETPHIEUNHAP
(
	MAHD VARCHAR(10),
	MAPN VARCHAR(10),
	SLNHANTHUCTE INT CHECK(SLNHANTHUCTE > 0)

		PRIMARY KEY(MAHD, MAPN)
		FOREIGN KEY(MAHD) REFERENCES DONDATHANG(MAHD),
	FOREIGN KEY(MAPN) REFERENCES PHIEUNHAPHANG(MAPN)
)

GO
