USE QLST
IF NOT EXISTS(SELECT * FROM SYS.types WHERE name = 'CART_ITEM')
	CREATE TYPE CART_ITEM AS TABLE
	(
		MASP VARCHAR(10),
		SOLUONG INT
	)
GO
DECLARE @CART_ITEM CART_ITEM
INSERT INTO @CART_ITEM
    (MASP, SOLUONG)
VALUES
    ('SP01', 10),
    ('SP02', 30)
EXEC USP_PROCESS_NEW_ORDER 'NV01', 'KH01', 'PG01', @CART_ITEM
GO

