USE master
GO

USE QLST
GO

CREATE OR ALTER PROCEDURE USP_REPORT_DAILY_SUMMARY_PHANTOM
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    BEGIN TRANSACTION
    BEGIN TRY

        DECLARE 
        @CurrentDate DATE = GETDATE();

        DECLARE @TongKH INT;
        DECLARE @TongDT BIGINT;

        SELECT 
            @TongKH = ISNULL(COUNT(DISTINCT MAKH),0),
            @TongDT = ISNULL(SUM(TONGTIEN), 0)
        FROM HOADON
        WHERE NGAYLAP = CAST(@CurrentDate AS DATE);

        PRINT N'WAITING...';
        WAITFOR DELAY '00:00:05'

        SELECT 
            N'Báo Cáo Ngày' AS TieuDe,
            @CurrentDate AS Ngay,
            @TongKH AS TongKhachHang,
            FORMAT(@TongDT, '#,##0') + ' VND' AS TongDoanhThu;

        -- SELECT 
        --     SP.MASP, 
        --     SP.TENSANPHAM, 
        --     SUM(CTHD.SOLUONG) AS SoLuongBan, 
        --     COUNT(DISTINCT HD.MAKH) AS SoKhachMua,
        --     FORMAT(SUM(CTHD.THANHTIEN), '#,##0') AS DoanhThuSanPham
        -- FROM SANPHAM SP
        -- JOIN CHITIETHOADON CTHD ON CTHD.MASP = SP.MASP
        -- JOIN HOADON HD ON CTHD.MAHD = HD.MAHD
        -- WHERE HD.NGAYLAP = CAST(@CurrentDate AS DATE)
        -- GROUP BY SP.MASP, SP.TENSANPHAM
        -- ORDER BY SoLuongBan DESC;
        COMMIT TRANSACTION

    END TRY

    BEGIN CATCH
        ROLLBACK TRANSACTION
        DECLARE @error NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@error, 16, 1)
    END CATCH
END

GO

DECLARE @Today DATE = GETDATE();
DECLARE @MaHD1 VARCHAR(10) = 'HD_TEST_01';
DECLARE @MaHD2 VARCHAR(10) = 'HD_TEST_02';

-- Clean data cũ
DELETE FROM CHITIETHOADON WHERE MAHD IN (@MaHD1, @MaHD2);
DELETE FROM HOADON WHERE MAHD IN (@MaHD1, @MaHD2);

-- Insert dữ liệu cho ngày hôm nay
INSERT INTO HOADON (MAHD, NGAYLAP, MANV, MAKH) VALUES
(@MaHD1, @Today, 'NV03', 'KH01'), 
(@MaHD2, @Today, 'NV03', 'KH03');

INSERT INTO CHITIETHOADON (MAHD, MASP, SOLUONG, THANHTIEN) VALUES
(@MaHD1, 'SP01', 10, 0), -- 10 Sữa
(@MaHD1, 'SP02', 2, 0),  -- 2 Chảo
(@MaHD2, 'SP01', 5, 0);  -- 5 Sữa


-- Chạy Procedure
EXEC USP_REPORT_DAILY_SUMMARY_PHANTOM;
EXEC USP_REPORT_DAILY_SUMMARY_PHANTOM;
GO